"""update site config

Revision ID: 1adde3c7a9fa
Revises: 5d720cc7074a
Create Date: 2025-11-18 13:57:28.180105

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1adde3c7a9fa'
down_revision = '5d720cc7074a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('youtube_link')
    with op.batch_alter_table('site_config', schema=None) as batch_op:
        batch_op.add_column(sa.Column('banner_image', sa.String(length=512), nullable=True))
        batch_op.drop_column('youtube_link')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('site_config', schema=None) as batch_op:
        batch_op.add_column(sa.Column('youtube_link', sa.VARCHAR(length=512), autoincrement=False, nullable=True))
        batch_op.drop_column('banner_image')

    op.create_table('youtube_link',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('url', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('youtube_link_pkey'))
    )
    # ### end Alembic commands ###
