"""empty message

Revision ID: 5d720cc7074a
Revises: b31bf7466b97
Create Date: 2025-11-18 13:05:32.020658

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d720cc7074a'
down_revision = 'b31bf7466b97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('youtube_link',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('youtube_link')
    # ### end Alembic commands ###
