"""Add SiteConfig model

Revision ID: b31bf7466b97
Revises: a2ffe7561af1
Create Date: 2025-11-18 12:40:12.084307

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b31bf7466b97'
down_revision = 'a2ffe7561af1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('site_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('youtube_link', sa.String(length=512), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('site_config')
    # ### end Alembic commands ###
