"""Create YoutubeLink table

Revision ID: e68d31517414
Revises: 1adde3c7a9fa
Create Date: 2025-11-23 21:49:23.306811

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e68d31517414'
down_revision = '1adde3c7a9fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('youtube_link',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('link', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('youtube_link')
    # ### end Alembic commands ###
